using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphLogic
{
    /// <summary>
    /// AN instance of a graph with an associate type for its vertices.
    /// </summary>
    /// <typeparam name="T">The data type for the vertices</typeparam>
    public interface IGraph<T>
    {
        /// <summary>
        /// Get the number of vertices in the graph
        /// </summary>
        int VertexCount { get; }
        
        /// <summary>
        /// Get the list of vertices in the graph
        /// </summary>
        IList<T> Vertices { get; }
        /// <summary>
        /// Get the vertex at the specified index.
        /// </summary>
        /// <param name="index">The index of the vertex</param>
        /// <returns>The vertex at the specified index</returns>
        T GetVertex(int index);

        /// <summary>
        /// Get the index of the specified vertex
        /// </summary>
        /// <param name="vertex">The vertex to determine its
        /// index of the underlying container</param>
        /// <returns>Returns the index of the vertex</returns>
        int GetIndex(T vertex);
        /// <summary>
        /// Get the neighbors of a vertex specified by the index.
        /// </summary>
        /// <param name="vertexIndex">The index of the vertex</param>
        /// <returns>Returns the neighbors of the vertex.</returns>
        IList<T> GetNeighbors(int vertexIndex);
        /// <summary>
        /// Get the neighbors of a vertex (using their indexes) specified by its index.
        /// </summary>
        /// <param name="vertexIndex">The index of the vertex.</param>
        /// <returns>Returns the neighbors (by their indexes) of vertex.</returns>
        IList<int> GetNeighborsByIndex(int vertexIndex);
        /// <summary>
        /// Get the degree of the vertex specified by its index.
        /// </summary>
        /// <param name="vertexIndex">The index of the vertex.</param>
        /// <returns>Returns the degree of the vertex (number of neighbors).</returns>
        int GetDegree(int vertexIndex);
        /// <summary>
        /// Get the degree of the vertex specified.
        /// </summary>
        /// <param name="vertex">The vertex to search</param>
        /// <param name="comparer">The comparer used to search
        /// for the vertex.</param>
        /// <returns>Returns the degree of the vertex.</returns>
        int GetDegree(T vertex, IComparer<T> comparer);

        /// <summary>
        /// Generates the adjacency matrix for the graph.
        /// </summary>
        int[,] AdjacencyMatrix { get; }

        /// <summary>
        /// Get the adjacency list of the graph.
        /// Contains a list of the vertices and its neighbors.
        /// The neighbors are specified using the index of the vertices.
        /// </summary>
        IList<IList<int>> Neighbors { get; }

        /// <summary>
        /// Performs a depth-first search then returns all the trees generated.
        /// </summary>
        /// <returns>Returns a list <see cref="Tree"/> generated by a depth-first search</returns>
        IList<Tree> DepthFirstSearch();

        /// <summary>
        /// Performs a dept-first search starting from the specified vertex index.
        /// </summary>
        /// <param name="vertexIndex">The starting vertex index to search.</param>
        /// <returns>>Returns the <see cref="Tree"/> generated by a depth-first search from the vertex index</returns>
        Tree DepthFirstSearch(int vertexIndex);

        /// <summary>
        /// Performs a breadth-first search then returns the trees generated
        /// </summary>
        /// <returns>Returns a list <see cref="Tree"/> generated by a depth-first search</returns>
        IList<Tree> BreadthFirstSearch();
        /// <summary>
        /// Performs a breadth-first search then returns all the trees generated.
        /// </summary>
        /// <param name="vertexIndex"></param>
        /// <returns>Returns the <see cref="Tree"/> generated by a depth-first search from the vertex index</returns>
        Tree BreadthFirstSearch(int vertexIndex);
    }
}
